apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootNodeJS-app
  labels:
    app: springbootNodeJS-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootNodeJS-app
  template:
    metadata:
      labels:
        app: springbootNodeJS-app
    spec:
      containers:
        - name: springbootNodeJS-app
          image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/springboot-java:5e2ac1a39acfd81317fefa65eacba031c4e2c4ac
          imagePullPolicy: Always
          ports:
            - containerPort: 8080