apiVersion: v1
kind: Service
metadata:
  name: springbootNodeJS-app-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: springbootNodeJS-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 3080